### ISSUE TITLE
Refactor actions for reusability (DRY)

### ISSUE THREAD

**Issue by joowdx** [eeneg/ticketing-mis#41]
# DRY (DON'T REPEAT YOURSELF)

Move **all** custom actions to namespaces `App\Filament\Actions`, `App\Filament\Actions\Tables`, `App\Filament\Actions\Tables\BulkActions` accordingly.

Make a trait for these action in `App\Filament\Actions\Traits` and implement it in its respective action. Implement your main logic in this trait.

_Check existing files for reference._

### Todo:

@MrckJd 
- [x] `UpdateRequestAction`
  - [x] Send notification to the requestor
- [x] `RejectAssignmentAction`
  - [x] Send notification to the officer 
- [x] `AcceptAssignmentAction`
  - [x] Send notification to the officer
- [x] `ScheduleRequestAction`
  - [x] Send notification to the requestor
- [x] `AdjustRequestAction`
  - [x] Send notification to the officer

@llAlcatrazll 
- [x] `AssignRequestAction` 
  - [x] Send notification to the assigned user
- [x] `ApproveRequestAction` — use approved status not accept
  - [x] Send notification to the requestor
- [x] `DeclineRequestAction` — use declined status not reject
  - [x] Add a required richeditor remarks form with placeholder "_Please provide a reason for declining this request_"
  - [x] Send notification to the requestor
- [x] Custom Notification with User Details, who, time and subject
